### ISSUE TITLE
REPORTING - Baseline & cible : ne pas faire apparaitre pour les désagrégations des variables et/ou les lieux de collecte, mais uniquement pour l'indicateur 

### ISSUE THREAD

**Issue by Maieule** [medecins-du-monde/monitool#102]

**Comment by romain-gilliotte** [comment]
Posera probleme car la page permet d'afficher des variables et des indicateurs sur le meme ecran.

On peut faire des essais et voir ce que ca donne

**Comment by Maieule** [comment]
#102 a été fusionné avec #105
