### ISSUE TITLE
problème avec icone de date

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#15]
les flèches suivante et précédente ne s'affiche pas correctement.

**Comment by romain-gilliotte** [comment]
Ça a été résolu dans le commit 1546e40974cd43528ae780dd5a7e384b82503b11

Pour résoudre le problème sur une installation déjà en ligne

    cd monitool/client/build
    sed -i "s/glyphicon/fa/g" monitool2.js
