### ISSUE TITLE
sauvegarde thématique malgré que l'on a pas toute les tradiuction

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#18]
dans la section paramètre -> Édition thématique, il serait bien de pouvoir sauvegarder meme si on a pas complété toute les langues.

je prend l'exemple, de MdM-Be b'a aucun mission en espagnol et donc verra aucune utilité pour complété l'espagnole.
Prenons example maintenant que l'on traduit le monitool en néerlandais, je pense que vous (MdM-Fr) trouverez inutile de le complété en néerlandais.

Je pense qu'il serai bien de rendre obligatoire uniquement l'anglais et non obligatoire les autre langue. et dans l'interface si la traduction dans la langue courante, il l'affichera en anglais

**Comment by romain-gilliotte** [comment]
On pourrait permettre de configurer la liste de langues disponibles dans la configuration et afficher ces champs en fonction.
