### ISSUE TITLE
bouton traduction automatique ne fonctionne pas

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#19]
testé sour Mac OSX avec chrome et firefox

**Comment by romain-gilliotte** [comment]
Le problème vient de la clef pour l'API de google translate qui est hardcodé dans le fichier [translate.js](https://github.com/medecins-du-monde/monitool/blob/94b0de5/client/dev/js/services/utils/translate.js#L11)

Il faudrait déplacer cette clef dans le fichier de configuration.

**Comment by romain-gilliotte** [comment]
Résolu dans le commit [bf24c8a5](https://github.com/medecins-du-monde/monitool/commit/bf24c8a52773d7647d130bc1389d24136312473f)
