### ISSUE TITLE
un simple clique dans les champs text dans la saisi

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#40]

**Comment by romain-gilliotte** [comment]
Je comprend pas.

Question, bug?
Tu peux être plus précis?

**Comment by SebastienBatteur** [comment]
j'ai fait quelque encodage. le problème c'est que le comportement standard  a été inversé. c'est a dire normalement quand tu fait un simple clic tu complète le champs la ou tu as cliqué et quand tu fait un double clic sa sélection tous le champs et remplacera tous le contenue par se que tu introduit.

ici c'est tous l'inverse, quand tu un simple clic  : 
- si sais le zero par défaut : il laisse le zero  et il complaise avec se que tu tape (visuellement)
- si il y a une valeur les donné sont effacé la valeur et il rajoute se que tu tape
et le double clic fait apparaitre le curseur de saisi dans le champs et tu peux modifier le texte existent

**Comment by romain-gilliotte** [comment]
C'est pour mimer le comportement de Excel.
Ton projet n'utilise aucune désagrégation?

![screenshot from 2017-03-30 11 12 31](https://cloud.githubusercontent.com/assets/1374063/24496872/df12fffe-1539-11e7-88b9-a9a764c8a691.png)

**Comment by SebastienBatteur** [comment]
pour le moment dans le projet du Niger, se sont des donnée simple.
Serait-il possible quand il n'y a pas de désagrégation de placer un champs input normal?
ceux si permettra de retrouvé une comportement logique en champs input et aussi avec le tab

**Comment by romain-gilliotte** [comment]
C'est possible :)
