### ISSUE TITLE
le bouton "Remplir avec les données de la période précédente" récupère la valeur de la 2eme donnée précédente

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#41]

**Comment by romain-gilliotte** [comment]
Je comprend pas ton point.

Ça récupère la valeur de la dernière saisie qui a été faite.

C'est pas le comportement que tu attends?
C'est pas le comportement que tu vois?

**Comment by SebastienBatteur** [comment]
ok, il semblerai avoir des un problème avec ce bouton. mais maintenant, j'essai de reproduire l'erreur et elle ne se reproduit plus.

sorry pour le derangement

**Comment by romain-gilliotte** [comment]
Reproduction du bug

[bug monitool.mov.zip](https://github.com/medecins-du-monde/monitool/files/882778/bug.monitool.mov.zip)

**Comment by romain-gilliotte** [comment]
C'est reproduit, et resolu!
