### ISSUE TITLE
Peut on utiliser un indicateur dans un autre indicateur?

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#43]

**Comment by romain-gilliotte** [comment]
Non, et jusqu'à nouvel ordre, on ne pourra pas.

Si on fait ça, 
1. Ça va devenir difficile de voir les erreurs de calcul
2. Ça va permettre aux utilisateurs de faire des boucles de calcul (des indicateurs qui se calculent mutuellement entre eux)
3. Il va falloir gerer la suppression d'indicateurs (conséquences quand on supprime un indicateurs qui est utilisé pour en calculer un autre)

**Comment by SebastienBatteur** [comment]
voici l'exemple suivent qui sont des donné utilisé par les indicateur et différent par lieux de collect
![capture d ecran 2017-03-30 a 11 09 01](https://cloud.githubusercontent.com/assets/2057112/24497274/30be2f08-153b-11e7-81e0-072e1adaf4c7.png)

la majorité des donnée sont calculé comme suit
![capture d ecran 2017-03-30 a 11 20 36](https://cloud.githubusercontent.com/assets/2057112/24497307/4830bdb8-153b-11e7-9271-c5547190fcb8.png)

il serai bien de pouvoir faire la meme chome pour évité des erreur d'encodage et également diminué le temps d'encodage  surtout si on a 20 a 30 lieux de collecte

**Comment by romain-gilliotte** [comment]
Tu peux utiliser les "formules personnalisées" pour calculer tes indicateurs dans ce cas.

![image](https://cloud.githubusercontent.com/assets/1374063/24501916/d8f7a478-154b-11e7-943e-c8ae8a5f0e6d.png)

**Comment by SebastienBatteur** [comment]
heu!! pas spécialement car ce table sers de dénominateur pour les indicateurs
de plus, si il faut changé la valeur, il faut repasser tous les indicateur pour changé la valeur. de plus ci elle est calculer
