### ISSUE TITLE
A-t-il un espace pour placer des données commun à tous les lieux de collecte?

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#44]

**Comment by romain-gilliotte** [comment]
Oui

Tu peux créer une source de données et indiquer qu'elle est collectée uniquement une fois pour tout le projet

![screenshot from 2017-03-30 10 38 37](https://cloud.githubusercontent.com/assets/1374063/24495362/2dca9652-1535-11e7-8415-0895beb6d193.png)
