### ISSUE TITLE
Utilisation du point au lieu de la virgule dans les chiffre décimaux

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#46]
avoir la possibilité de choisir le séparateur décimaux

**Comment by romain-gilliotte** [comment]
On ne travaille que avec des valeurs entières dans monitool.
Le cas d'utilisation présenté pour utiliser cette feature ne justifie pas son implementation.

A re-ouvrir dans le futur si on trouve un cas d'utilisation valide.
