### ISSUE TITLE
avoir une source de donnée  d'une valeur fixe qui évolue de le temps

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#48]
Exemple : 
evolution de population : 38111 * 1,039 ^(  Y - 2014)
    Y = anne current
nombre de natalité estimé  par la valeur colonne: 38111 * 1,039 ^(  Y - 2014) *  0,04 / valeurColonne
    Y = anne current
   valeurColonne = 12 par mois , 3 par trimestre, 52 par semaine

ceux-si permettra de calcul les dominateurs pour chaque intervalle

**Comment by romain-gilliotte** [comment]
Après discussion, on veut forcer les utilisateurs à rentrer leurs données qui sont projetés, pour qu'ils realisent bien la fragilité de leurs calculs
+ jugé trop compliqué pour l'utilisateur de rentrer des formules justes
