### ISSUE TITLE
les lignes ne se supprime pas aprés la modification des période et la suppression des données

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#49]
![capture d ecran 2017-03-30 a 16 26 02](https://cloud.githubusercontent.com/assets/2057112/24509095/bee98a6e-1565-11e7-8aab-6af010e35546.png)

**Comment by romain-gilliotte** [comment]
En fait tu as fait des saisies sur des lieux qui sont pas dans ce tableau, car supprimés de cette source de données.

Mais c'est bien un bug!

Il va dans ma liste de problèmes à résoudre avec les autres...
