### ISSUE TITLE
Cible inférieur à un valeur

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#51]

**Comment by romain-gilliotte** [comment]
C'est à dire?

**Comment by SebastienBatteur** [comment]
exemple le nombre de mortalité l'objectif doit être inférieur et pas supérieur à

**Comment by romain-gilliotte** [comment]
Si tu mets une baseline supérieure à la cible, Monitool comprend automatiquement et met les bonnes couleurs dans le tableau

Ca suffit, ou tu as besoin de plus?

**Comment by SebastienBatteur** [comment]
oui mais faudra pas oublier de le documenté à l'utilisateur
