### ISSUE TITLE
changement de lieu de collect et de période d'une source de donnée fait craché le service dans statistique général

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#53]
procédure pour créé le problème: 
- créez une source  avec tous le projet en lieu de collecte
- créez une question
- ajoutez des données dans la saisi de cette source de donnée
- changez le lieux de collecte 
- allez dans statistiques générales
:boom: service dead

**Comment by romain-gilliotte** [comment]
J'arrive pas à reproduire sur la branche dev.
A tenter sur la branche master.

**Comment by romain-gilliotte** [comment]
j'arrive pas à reproduire => ferme
