### ISSUE TITLE
rajouter baseline et cible dans l'affichage du reporting

### ISSUE THREAD

**Issue by romain-gilliotte** [medecins-du-monde/monitool#59]

**Comment by Maieule** [comment]
rajouter baseline et target sur le graphique si possible

**Comment by romain-gilliotte** [comment]
Sur le graphique c'est pas vraiment possible.
Comment faire? On peut mettre des lignes horizontales, mais ça rend le graphique illisible, surtout si on y affiche plusieurs indicateurs.

On peut aussi faire que la ligne qu'on affiche est plus ou moins epaisse / de couleur differente si on est sous la target, mais c'est encore moins clair.

On peut eventuellement changer le fonctionement des graphiques, et faire qu'on puisse afficher un seul indicateur à la fois si vous voulez.
En attendant j'ai rajouté les baseline et target sur les 3 pages de rapports
