### ISSUE TITLE
Pouvoir mettre des limites sur les valeurs saisies à la conception du formulaire

### ISSUE THREAD

**Issue by romain-gilliotte** [medecins-du-monde/monitool#71]
avoir la possibilité de limiter certaines valeur aberantes dans la saisie ou au moins rendre visible la présence de chiffres à priori aberrant (donc avoir la possibilité de mettre un min / max dans les sources des données)

**Comment by romain-gilliotte** [comment]
Avec du recul, les pages de saisie mettent en rouge les saisies invalides.
On pourrait mettre en jaune celles qui sont hors des limites (sans les interdire).

**Comment by Maieule** [comment]
#71 a été fusionné avec #95
