### ISSUE TITLE
dans le fichier config "ID de répertoire" d'azure

### ISSUE THREAD

**Issue by SebastienBatteur** [medecins-du-monde/monitool#75]
dans les url de authorizationURL et de tokenURL qui contient le "common". celui-ci peut être remplacé dans le fichier config car il peut être remplacé par "ID de répertoire" d'azure ( voir capture d'ecran )

ceux-ci évitera a l'utilisateur de confirmer que l'application accédera à ces données
![capture d ecran 2017-05-12 a 11 00 50](https://cloud.githubusercontent.com/assets/2057112/25991360/26062aae-3703-11e7-943a-fc3ceedc626b.png)

**Comment by romain-gilliotte** [comment]
Ca permet que microsoft presente pas la page d'autorisation de l'application?

**Comment by SebastienBatteur** [comment]
évité d'avoir ce message
![capture d ecran 2017-05-13 a 18 02 44](https://cloud.githubusercontent.com/assets/2057112/26026993/6edba2d2-3806-11e7-8c5e-af465cf507ce.png)

**Comment by romain-gilliotte** [comment]
Cool
Je presenterais un patch pour remettre ça dans la config

**Comment by SebastienBatteur** [comment]
il faudrai tester si se que je dit est juste pour évité le de faire du travail pour rien.
personnellement, je n'ai pas la temps (dernier jour temps plain hier)
