### ISSUE TITLE
Precise node modules versions

### ISSUE THREAD

**Issue by Yago** [medecins-du-monde/monitool#78]
Using `x` version is really dangerous and not recommended by the official [NPM documentation](https://docs.npmjs.com/files/package.json#dependencies). Normally, you should use `*` instead, but it's still a dangerous practice. If there is only one of your dependency who moves into a new breaking change major version and all your install will break.

In my case, I just install Monitool and `/authentication/login-training` seems already broken by the `nano.js`.

Is it possible to reverse engineer your working instance and add more restricted versions in the `package.json`

**Comment by romain-gilliotte** [comment]
Sorry for this...
I'll update the package.json file ASAP.

In the meantime, I pushed a package lock file so that npm uses the same versions I have on my computer,
