### ISSUE TITLE
Certains comptes utilisateurs ne peuvent pas créer de nouveaux projets (GenCo Phillipines et MedCo Bulgarie)

### ISSUE THREAD

**Issue by Maieule** [medecins-du-monde/monitool#89]

**Comment by romain-gilliotte** [comment]
Ce n'est pas un bug.

Ces comptes ne sont pas autorisés à créer des projets. C'est le cas de la très grande majorité des comptes.

Tu peux changer leurs droits dans les paramètres

![image](https://user-images.githubusercontent.com/1374063/36781141-b564ede2-1c7d-11e8-8253-4cec75450073.png)
