### ISSUE TITLE
User : ajouter statut saisie + rapport

### ISSUE THREAD

**Issue by Maieule** [medecins-du-monde/monitool#98]

**Comment by Maieule** [comment]
Les personnes qui saisissent ne voient pas la section reporting, ce qui est important pour voir le résulta(t de leur saisie et avoir la vision globale des résultats, améliorer la qualité, si besoin alerter la personne en charge du système et ainsi participer aux analyse

**Comment by romain-gilliotte** [comment]
Tout le monde a accès à la partie reporting.

Contacter la personne qui a fait remonter le probleme pour discuter de son besoin?
Ticket à fermer sinon

**Comment by Maieule** [comment]
#98 a été fusionné avec #113
