### ISSUE TITLE
RAPPORT : ajouter une sous section Dashboard à paramétrer par chaque projet (planification de graphiques et tableaux)

### ISSUE THREAD

**Issue by Maieule** [medecins-du-monde/monitool#99]

**Comment by Maieule** [comment]
The objective is to give the possibility for each project to set their own dashboard according their needs in terms of monitoring and reporting : 
- Select the time (by month or by semester ...)
- Select variables and/or indicators, types of graphics and/or tables
- For each graphic and table possibility to write (comment, analysis, recommandations, actions to be taken...)

**Comment by romain-gilliotte** [comment]
Trop gros travail.
Apres discussion, plutot s'orienter vers permettre de brancher un outil de BI (power bi, ...) sur monitool pour faire du transversal

Ticket a fermer si tout le monde est d'accord
